### PR TITLE
Use our own fork of issue-labeler

### PR DESCRIPTION
**Pull request by cor3ntin**
Import our own fork of issue labeler that only adds the 'new issue' if no other label is set
https://github.com/llvm/llvm-project/issues/65701#issuecomment-1712803305

### CODE REVIEW

**Comment by tru** [comment]
Is this a subtree or how did you add that? It doesn't really render well in GitHub - but I guess that's what it is?

**Comment by cor3ntin** [comment]
I did add a subtree, pushed on my forked, made a PR. First time using subtrees so i hope i got that right!

**Review by tru — APPROVED** [review]
Let's merge this so we can fix the issue with the current lableler.

**Comment by cor3ntin** [comment]
@tru I don't have access  here, feel free to merge it or to give me access, whichever is more convenient :)

**Comment by tru** [comment]
I don't have access either. @tstellar can you help out?

**Comment by tstellar** [comment]
It's not giving me the option to merge at the moment, do you need to rebase it?

**Comment by cor3ntin** [comment]
@tstellar nope, weird! 
image

**Comment by tstellar** [comment]
OK, I see. It won't let me rebase and merge, but I can merge it with a merge commit.  Is a merge commit OK?

**Comment by cor3ntin** [comment]
@tstellar SGTM

**Pull request merged**
